<?php

declare(strict_types=1);

namespace ContextDiscovery\Tests\Unit\Adapters\Autoload;

use ContextDiscovery\Adapters\Autoload\ComposerPsr4ClassLocator;
use ContextDiscovery\Tests\Fakes\FakeSourceRepository;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * M6 · Composer's generated PSR-4 map, read as **location** metadata (ADR-A014).
 *
 * A standard Laravel application declares `App\` in its `composer.json` and nothing else, so every
 * framework name is unplaceable however many packages are installed. Composer already knows where
 * they are; this reads that table instead of inventing one.
 *
 * Two properties carry the whole decision, and each has its own test below:
 *
 * - **Parsed, never executed.** The file is PHP from the repository under review. `require` would
 *   run it outside the root-scoping every other read goes through, so the reader recovers the map
 *   from string literals and evaluates nothing.
 * - **Location, not ownership.** A widened map makes a dependency class *locatable*; whether its
 *   source may be fetched is still `isProjectSource()`'s answer. That separation is what keeps this
 *   from undoing ADR-A012 and ADR-A013 — and it is asserted here as well as in the fixture.
 */
final class ComposerGeneratedMapTest extends TestCase
{
    /**
     * The real shape, transcribed from a `laravel/framework` v12.64.0 install: `$vendorDir` and
     * `$baseDir` roots, a multi-directory entry, an overlapping shorter prefix, and the project's
     * own namespace carried alongside the dependencies'.
     */
    private const GENERATED = <<<'PHP'
        <?php

        // autoload_psr4.php @generated by Composer

        $vendorDir = dirname(__DIR__);
        $baseDir = dirname($vendorDir);

        return array(
            'Symfony\\Polyfill\\Uuid\\' => array($vendorDir . '/symfony/polyfill-uuid'),
            'Illuminate\\Support\\' => array($vendorDir . '/laravel/framework/src/Illuminate/Macroable', $vendorDir . '/laravel/framework/src/Illuminate/Collections'),
            'Illuminate\\' => array($vendorDir . '/laravel/framework/src/Illuminate'),
            'App\\' => array($baseDir . '/app'),
        );
        PHP;

    // ---------------------------------------------------------------- dependency resolution

    #[DataProvider('dependencyClasses')]
    public function testAnInstalledDependencyBecomesLocatable(string $class, string $path): void
    {
        self::assertSame($path, $this->locator()->pathFor($class));
    }

    /**
     * @return iterable<string, array{string, string}>
     */
    public static function dependencyClasses(): iterable
    {
        yield 'facade' => [
            'Illuminate\Support\Facades\Log',
            'vendor/laravel/framework/src/Illuminate/Support/Facades/Log.php',
        ];
        // Str is under no `Illuminate\Support\` directory: it is found only by falling back to the
        // shorter `Illuminate\` prefix, which is the overlapping-prefix case.
        yield 'shorter prefix wins on fall-through' => [
            'Illuminate\Support\Str',
            'vendor/laravel/framework/src/Illuminate/Support/Str.php',
        ];
        // Arr and Collection are under `Collections/`, the second of the longer prefix's directories.
        yield 'second directory of a multi-directory prefix' => [
            'Illuminate\Support\Arr',
            'vendor/laravel/framework/src/Illuminate/Collections/Arr.php',
        ];
        yield 'collection' => [
            'Illuminate\Support\Collection',
            'vendor/laravel/framework/src/Illuminate/Collections/Collection.php',
        ];
        yield 'an unrelated package' => [
            'Symfony\Polyfill\Uuid\Uuid',
            'vendor/symfony/polyfill-uuid/Uuid.php',
        ];
    }

    public function testABaseDirEntryResolvesRelativeToTheRepositoryRoot(): void
    {
        // `$baseDir . '/app'` is the repository root, which is '' in the relative paths this class
        // deals in — so the entry must land on `app/…` and not on `/app/…`.
        self::assertSame('app/Models/Package.php', $this->locator()->pathFor('App\Models\Package'));
    }

    // ---------------------------------------------------------------- location is not ownership

    public function testLocatingADependencyDoesNotMakeItProjectSource(): void
    {
        $locator = $this->locator();

        self::assertNotNull($locator->pathFor('Illuminate\Support\Str'), 'locatable');
        self::assertFalse(
            $locator->isProjectSource('vendor/laravel/framework/src/Illuminate/Support/Str.php'),
            'and still a dependency — this is what stops M4 and M5 from being undone'
        );
        self::assertTrue($locator->isProjectSource('app/Models/Package.php'));
    }

    // ---------------------------------------------------------------- project precedence

    public function testTheProjectsOwnDirectoriesAreTriedFirst(): void
    {
        // The project declares a prefix the generated map also carries. Its own directory holds the
        // class, so that is the answer.
        $locator = $this->locatorWith(
            ['Illuminate\\' => 'app/Overrides/Illuminate/'],
            ['app/Overrides/Illuminate/Support/Str.php' => '<?php', 'vendor/laravel/framework/src/Illuminate/Support/Str.php' => '<?php']
        );

        self::assertSame('app/Overrides/Illuminate/Support/Str.php', $locator->pathFor('Illuminate\Support\Str'));
        self::assertTrue($locator->isProjectSource('app/Overrides/Illuminate/Support/Str.php'), 'and it is the project\'s');
    }

    public function testAProjectPrefixStillFallsThroughWhenItDoesNotHoldTheClass(): void
    {
        // "The project wins" means tried first, not exclusively — which is what Composer itself
        // does with multiple directories on one prefix.
        $locator = $this->locatorWith(
            ['Illuminate\\' => 'app/Overrides/Illuminate/'],
            ['vendor/laravel/framework/src/Illuminate/Support/Str.php' => '<?php']
        );

        self::assertSame('vendor/laravel/framework/src/Illuminate/Support/Str.php', $locator->pathFor('Illuminate\Support\Str'));
    }

    // ---------------------------------------------------------------- unknown

    public function testAClassOutsideEveryMappingRemainsUnplaceable(): void
    {
        self::assertNull($this->locator()->pathFor('Nowhere\At\All'));
        self::assertNull($this->locator()->pathFor('App\Contracts\MissingGateway'), 'mapped prefix, absent file');
    }

    // ---------------------------------------------------------------- degraded metadata

    #[DataProvider('degradedMetadata')]
    public function testDegradedMetadataFallsBackToTheProjectMapWithoutRaising(string $label, ?string $generated): void
    {
        $files = ['composer.json' => $this->manifest([]), 'app/Models/Package.php' => '<?php'];

        if ($generated !== null) {
            $files['vendor/composer/autoload_psr4.php'] = $generated;
        }

        $locator = new ComposerPsr4ClassLocator(new FakeSourceRepository($files));

        self::assertNull($locator->pathFor('Illuminate\Support\Str'), $label . ': nothing is merged');
        self::assertSame('app/Models/Package.php', $locator->pathFor('App\Models\Package'), $label . ': the project map still works');
    }

    /**
     * @return iterable<string, array{string, string|null}>
     */
    public static function degradedMetadata(): iterable
    {
        yield 'no vendor directory at all' => ['absent', null];
        yield 'empty file' => ['empty', ''];
        yield 'truncated' => ['truncated', "<?php\n\nreturn array(\n    'Illuminate\\\\' => arr"];
        yield 'not PHP at all' => ['garbage', 'this is not composer output ]]] {{{'];
        yield 'valid PHP, wrong shape' => ['wrong shape', "<?php\n\nreturn 'a string';\n"];
    }

    public function testTheGeneratedFileIsParsedAndNeverExecuted(): void
    {
        // If the reader used `require`, this file's side effect would happen. It must not.
        $locator = new ComposerPsr4ClassLocator(new FakeSourceRepository([
            'composer.json' => $this->manifest([]),
            'vendor/composer/autoload_psr4.php' => "<?php\n\ndefine('CONTEXT_DISCOVERY_M6_EXECUTED', true);\n\n"
                . "\$vendorDir = dirname(__DIR__);\n\nreturn array(\n"
                . "    'Illuminate\\\\' => array(\$vendorDir . '/laravel/framework/src/Illuminate'),\n);\n",
            'vendor/laravel/framework/src/Illuminate/Support/Str.php' => '<?php',
        ]));

        self::assertSame(
            'vendor/laravel/framework/src/Illuminate/Support/Str.php',
            $locator->pathFor('Illuminate\Support\Str'),
            'the map was still read'
        );
        self::assertFalse(
            defined('CONTEXT_DISCOVERY_M6_EXECUTED'),
            'the file is PHP from the repository under review; reading it must never run it'
        );
    }

    // ---------------------------------------------------------------- determinism

    public function testTheSameTreeAlwaysGivesTheSamePath(): void
    {
        self::assertSame(
            $this->locator()->pathFor('Illuminate\Support\Arr'),
            $this->locator()->pathFor('Illuminate\Support\Arr'),
            'P8'
        );
    }

    public function testTheVendorDirectoryIsHonouredWhenRelocated(): void
    {
        $locator = new ComposerPsr4ClassLocator(new FakeSourceRepository([
            'composer.json' => (string) json_encode([
                'config' => ['vendor-dir' => 'third-party'],
                'autoload' => ['psr-4' => ['App\\' => 'app/']],
            ]),
            'third-party/composer/autoload_psr4.php' => self::GENERATED,
            'third-party/laravel/framework/src/Illuminate/Support/Str.php' => '<?php',
        ]));

        self::assertSame('third-party/laravel/framework/src/Illuminate/Support/Str.php', $locator->pathFor('Illuminate\Support\Str'));
        self::assertFalse($locator->isProjectSource('third-party/laravel/framework/src/Illuminate/Support/Str.php'));
    }

    // ---------------------------------------------------------------- fixtures

    private function locator(): ComposerPsr4ClassLocator
    {
        return $this->locatorWith([], []);
    }

    /**
     * @param array<string, string> $projectPrefixes
     * @param array<string, string> $extraFiles
     */
    private function locatorWith(array $projectPrefixes, array $extraFiles): ComposerPsr4ClassLocator
    {
        return new ComposerPsr4ClassLocator(new FakeSourceRepository(array_merge([
            'composer.json' => $this->manifest($projectPrefixes),
            'vendor/composer/autoload_psr4.php' => self::GENERATED,
            'app/Models/Package.php' => '<?php',
            'vendor/symfony/polyfill-uuid/Uuid.php' => '<?php',
            'vendor/laravel/framework/src/Illuminate/Support/Facades/Log.php' => '<?php',
            'vendor/laravel/framework/src/Illuminate/Support/Str.php' => '<?php',
            'vendor/laravel/framework/src/Illuminate/Collections/Arr.php' => '<?php',
            'vendor/laravel/framework/src/Illuminate/Collections/Collection.php' => '<?php',
        ], $extraFiles)));
    }

    /**
     * @param array<string, string> $extraPrefixes
     */
    private function manifest(array $extraPrefixes): string
    {
        return (string) json_encode([
            'autoload' => ['psr-4' => array_merge(['App\\' => 'app/'], $extraPrefixes)],
        ]);
    }
}
